name: Rust

on: ['push']

jobs:
  ci:
    strategy:
      matrix:
        rust: [stable, beta, nightly]
        os: [macos-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        name: Setup 
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - uses: actions-rs/cargo@v1
        name: Build
        with:
          command: build

      - uses: actions-rs/cargo@v1
        name: Test
        with:
          command: test

      - uses: actions-rs/cargo@v1
        name: Fmt
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1
        name: Clippy
        with:
          command: clippy
          args: -- -D warnings
